feat: add blog post proposal for messaging v1.4
arcus-azure/arcus pull request #284
Opened 2023-01-06 10:26 UTC by stijnmoreels

Propose new blog post for Arcus Messaging v1.4 release.

Relates to #282

2023-01-06 10:43 UTC, pim-simons requested changes

2023-01-06 10:43 UTC, pim-simons commented on community/blog/2023-01 Integrating fully with Microsoft technology in Arcus Messaging v1.4/README.md
> +Microsoft uses internally the new W3C correlation technology to track connections between services. In short: this is possible by passing on a `traceparent` value that contains both the current trans
```suggestion
Microsoft internally uses the new W3C correlation technology to track connections between services. In short: this is possible by passing on a `traceparent` value that contains both the current transaction ID that is the same across the entire operation call, as well as the parent ID that identifies the sender. Microsoft uses this value when an HTTP request is made with the built-in `HttpClient`, when a message is placed on an Azure Service Bus queue, when a SQL command is executed, and any other Microsoft/Azure-related technology.
```

2023-01-06 10:43 UTC, pim-simons commented on community/blog/2023-01 Integrating fully with Microsoft technology in Arcus Messaging v1.4/README.md
> +Arcus was using in the past the Hierarchical correlation system which was not only deprecated but did not by default matches the W3C correlation that Microsoft uses. The new v1.4 release is changed c
```suggestion
In the past Arcus was using the Hierarchical correlation system which was not only deprecated but did not by default match the W3C correlation that Microsoft uses. The new v1.4 release is changed completely in that regard. Now, W3C is the default which means that any message that comes from Azure Service Bus or Azure EventHubs will automatically get tracked without the sender needing to know about any Arcus technology on the sending side. This is a major improvement that provides real added value for projects. Arcus and Microsoft are now working seamlessly together.
```

2023-01-06 11:30 UTC, pim-simons approved these changes

2023-01-09 12:09 UTC, fgheysels approved these changes

2023-01-09 12:09 UTC, merged